#!/bin/sh
########################################## Notes

NOTEDIR=~/usr/doc/notes

function list_files {
    for notefile in $(ls $NOTEDIR | grep .md); do 
        printf "%s\n\t%s\n" $notefile "$(head -1 $NOTEDIR/$notefile | sed 's/#//g' )"
    done
}

function find_files { 
    ls $NOTEDIR | grep "$NOTEDIR/$1.md" | head -n 1 | xargs $EDITOR
}

function list_headers {
    for notefile in $(ls $NOTEDIR | grep .md); do 
        printf "\n"
        grep -B 1 "====" $NOTEDIR/$notefile
        grep -B 1 "----" $NOTEDIR/$notefile
        grep "#" $NOTEDIR/$notefile
    done
}

function find_header {
    IFS=: read f l h <<< $(ag --nogroup "#" $NOTEDIR/*.md | grep -i "$@" | head -n1)
    if [[ $f ]]; then
        $EDITOR $f +$l 
    else
        echo "no header found."
    fi
}

while getopts "fh" flag; do
   case $flag in
       f ) file_mode=1 ;;
       h ) header_mode=1 ;;
       * ) echo "can't understand that.";;
   esac 
done
shift $(( OPTIND - 1 ))

if [[ ! $1 ]]; then
    test $file_mode && list_files ''
    test $header_mode && list_headers ''
else
    echo $1
    test $file_mode && find_files $1
    test $header_mode && find_header $1
fi
