#!/bin/sh
########################################## Notes

NOTEDIR=~/usr/doc/notes


function usage {
cat << eof
usage: $(basename $0) [-f filename] [-h headername] TEXT
Find a string in a file and edit the file.

Options:
    -f : A filename (or a regex) to look for.
eof
}


while getopts "f:" flag; do
   case $flag in
       f ) file_regex=$OPTARG ;;
       * ) usage; exit 1 ;;
   esac 
done
shift $(( OPTIND - 1 ))

filenames=$(ls -1 $NOTEDIR)
test $file_regex && filenames=$(echo "$filenames" | grep $file_regex)
if [[ $* ]]; then
    IFS=: read f l t <<< $(echo "$filenames" | xargs ag --nogroup "$*" | head -1)
else
    f=$(echo "$filenames" | head -1)
fi
if [[ $f ]]; then
    $EDITOR $f +$l
else
    echo "Couldn't find anything."
fi
